
language: node_js
node_js: node
services:
  - postgresql
before_script:
  - psql -U postgres -c 'CREATE DATABASE "object_tracker_test";'
  - psql -U postgres -f ./db/objectsdb.sql -d object_tracker_test